# Generated by Django 3.2.7 on 2021-11-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='img',
        ),
        migrations.AddField(
            model_name='img',
            name='img_cus',
            field=models.ImageField(null=True, upload_to='im/'),
        ),
    ]
